package fund.cyber.markets.common

const val KAFKA_BROKERS = "KAFKA_BROKERS"
const val KAFKA_BROKERS_DEFAULT = "localhost:9092"

const val CASSANDRA_HOSTS = "CASSANDRA_HOSTS"
const val CASSANDRA_HOSTS_DEFAULT = "localhost"

const val CASSANDRA_PORT = "CASSANDRA_PORT"
const val CASSANDRA_PORT_DEFAULT = 9042

const val EXCHANGES_CONNECTOR_API_URLS = "EXCHANGES_CONNECTOR_API_URLS"
const val EXCHANGES_CONNECTOR_API_URLS_DEFAULT = "http://localhost:8080"

const val EXCHANGES = "EXCHANGES"
const val EXCHANGES_DEFAULT = "bitfinex,bitflyer,binance,bitstamp,gdax,gemini,hitbtc,okcoin,okex,poloniex,etherdelta"

const val PARITY_URL = "PARITY_URL"
const val PARITY_URL_DEFAULT = "http://127.0.0.1:8545"

const val WINDOW_INTERVALS_MIN = "WINDOW_INTERVALS_MIN"
const val WINDOW_INTERVALS_MIN_DEFAULT = "1,5,15,30,60,180,240,360,720,1440"

const val WINDOW_HOP_SEC = "WINDOW_HOP_SEC"
const val WINDOW_HOP_SEC_DEFAULT = 3

const val ALLOW_NOT_CLOSED_WINDOWS = "ALLOW_NOT_CLOSED_WINDOWS"
const val ALLOW_NOT_CLOSED_WINDOWS_DEFAULT = true

const val ORDERBOOK_SNAPSHOT_PERIOD_MIN = "ORDERBOOK_SNAPSHOT_PERIOD_MIN"
const val ORDERBOOK_SNAPSHOT_PERIOD_MIN_DEFAULT: Long = 10

const val SAVE_ORDERBOOKS = "SAVE_ORDERBOOKS"
const val SAVE_ORDERBOOKS_DEFAULT = true

const val LAG_FROM_REAL_TIME_MIN = "LAG_FROM_REAL_TIME_MIN"
const val LAG_FROM_REAL_TIME_MIN_DEFAULT: Long = 60 * 3

const val CORS_ALLOWED_ORIGINS = "CORS_ALLOWED_ORIGINS"
const val CORS_ALLOWED_ORIGINS_DEFAULT = "cybermarkets.sh"