# Container with application
FROM confluentinc/cp-kafka-connect:3.3.0
MAINTAINER Name <mgergalov@gmail.com>
ENV CONNECT_PLUGIN_PATH=/etc/kafka-connect/custom-plugins
COPY . /etc/kafka-connect/custom-plugins