INSERT INTO markets.trade (epoch_h, tradeId, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418328, '1', 'poloniex', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418328, '2','poloniex', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418328, '4','poloniex', 1505982561, 'SELL', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418328, '3', 'hitbtc', 1505982562, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418329, '23', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '17', 'bbbbbbb', 1505982561, 'SELL', { baseToken: 'cccc', quoteToken: 'dddd' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '89', 'bbbbbbb', 1505982562, 'SELL', { baseToken: 'aaaa', quoteToken: 'bbbb' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '19', 'aaaaa', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '10', 'aaaaa', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '110', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '170', 'bbbbbbb', 1505982561, 'SELL', { baseToken: 'cccc', quoteToken: 'dddd' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '819', 'bbbbbbb', 1505982562, 'SELL', { baseToken: 'aaaa', quoteToken: 'bbbb' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '255', 'aaaaa', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '105', 'aaaaa', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '333', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '332', 'hitbtc', 1505982561, 'SELL', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '331', 'hitbtc', 1505982562, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '329', 'poloniex', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '326', 'poloniex', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418327, '327', 'hitbpoloniextc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeId, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418325, '201', 'poloniex', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '202','poloniex', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '204','poloniex', 1505982561, 'SELL', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '203', 'hitbtc', 1505982562, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '223', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '217', 'bbbbbbb', 1505982561, 'SELL', { baseToken: 'cccc', quoteToken: 'dddd' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '289', 'bbbbbbb', 1505982562, 'SELL', { baseToken: 'aaaa', quoteToken: 'bbbb' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '219', 'aaaaa', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '210', 'aaaaa', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2110', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2170', 'bbbbbbb', 1505982561, 'SELL', { baseToken: 'cccc', quoteToken: 'dddd' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2819', 'bbbbbbb', 1505982562, 'SELL', { baseToken: 'aaaa', quoteToken: 'bbbb' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2255', 'aaaaa', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2105', 'aaaaa', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2333', 'hitbtc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2332', 'hitbtc', 1505982561, 'SELL', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2331', 'hitbtc', 1505982562, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2329', 'poloniex', 1505982559, 'SELL', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2326', 'poloniex', 1505982560, 'BUY', { baseToken: 'BTC', quoteToken: 'USDT' }, 2.00, 8026.0234, 4013.88231834
);

INSERT INTO markets.trade (epoch_h, tradeid, exchange, date, tradetype, pairInitializer, baseamount, quoteamount, spotprice) VALUES (
418322, '2327', 'hitbpoloniextc', 1505982563, 'BUY', { baseToken: 'BTC', quoteToken: 'USD' }, 2.00, 8026.0234, 4013.88231834
);